StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{60AC9C2910B78278}" {
   Id "KSC-Task_Destroy_Description"
   Target_en_us "Destroy the designated target."
   Target_de_de "Zerstören Sie das angegebene Ziel."
   Modified 1621926863
   Author "kexanone"
   LastChanged "kexanone"
  }
  CustomStringTableItem "{60AC9C291F293C90}" {
   Id "KSC-Task_Destroy_Name"
   Target_en_us "Destroy %1"
   Target_de_de "Zerstöre %1"
   Modified 1621926835
   Author "kexanone"
   LastChanged "kexanone"
  }
  CustomStringTableItem "{60ACDABEF48FC58E}" {
   Id "KSC-Task_FindIntel_Description"
   Target_en_us "Recover intel from enemy forces."
   Target_de_de "Stehle Informationsmaterial von den feindlichen Einheiten."
   Modified 1621949621
   Author "kexanone"
   LastChanged "kexanone"
  }
  CustomStringTableItem "{60ACDABEF3693FC3}" {
   Id "KSC-Task_FindIntel_Name"
   Target_en_us "Recover %1"
   Target_de_de "Finde %1"
   Modified 1621949188
   Author "kexanone"
   LastChanged "kexanone"
  }
  CustomStringTableItem "{60ACDABEC832AEB8}" {
   Id "KSC-Task_Kill_Description"
   Target_en_us "Kill the HVT at the designated location."
   Target_de_de "Töte das hochrangige Ziel am angegeben Ort."
   Modified 1621949819
   Author "kexanone"
   LastChanged "kexanone"
  }
  CustomStringTableItem "{60ACDABECC98FAA8}" {
   Id "KSC-Task_Kill_Name"
   Target_en_us "Kill %1"
   Target_de_de "Töte %1"
   Modified 1621949644
   Author "kexanone"
   LastChanged "kexanone"
  }
 }
}