StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{61597E9CD282A9B3}" {
   Id "KSC-Item_IntelFolder_Description"
   Target_en_us "May contain secrets."
   Target_de_de "Hat möglicherweise geheime Informationen."
   Modified 1633289427
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{61597E9CD93DBD5E}" {
   Id "KSC-Item_IntelFolder_Name"
   Target_en_us "Intelligence Folder"
   Target_de_de "Geheime Dokumente"
   Modified 1633289299
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{624EF04DA8276D64}" {
   Id "KSC-Task_Build_Description"
   Target_en_us "Build the specified structure in the area."
   Target_de_de "Baue die angegebene Struktur in dem Gebiet."
   Modified 1649340715
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{624EF04DB6865394}" {
   Id "KSC-Task_Build_Name"
   Target_en_us "Build %1"
   Target_de_de "Baue %1"
   Modified 1649340600
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{66FC0A2F1C5EA7A6}" {
   Id "KSC-Task_Capture_Description"
   Target_en_us "Capture the HVT at the designated location."
   Target_de_de "Nimm das hochrangige Ziel fest am angegeben Ort."
   Modified 1727854370
   Author "Kex"
   LastChanged "Kex"
  }
  CustomStringTableItem "{66FC0A2F1AC97372}" {
   Id "KSC-Task_Capture_Name"
   Target_en_us "Capture %1"
   Target_de_de "Nimm %1 fest"
   Modified 1727854380
   Author "Kex"
   LastChanged "Kex"
  }
  CustomStringTableItem "{61530DEFF898BB6E}" {
   Id "KSC-Task_ClearArea_Description"
   Target_en_us "Clear the specified area."
   Target_de_de "Sichere das gegebene Gebiet."
   Modified 1632834224
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{61530DEFC727D0BC}" {
   Id "KSC-Task_ClearArea_Name"
   Target_en_us "Clear %1"
   Target_de_de "Sichere %1"
   Modified 1632834190
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{60AC9C2910B78278}" {
   Id "KSC-Task_Destroy_Description"
   Target_en_us "Destroy the designated target."
   Target_de_de "Zerstören Sie das angegebene Ziel."
   Modified 1621926863
   Author "kexanone"
   LastChanged "kexanone"
  }
  CustomStringTableItem "{60AC9C291F293C90}" {
   Id "KSC-Task_Destroy_Name"
   Target_en_us "Destroy %1"
   Target_de_de "Zerstöre %1"
   Modified 1621926835
   Author "kexanone"
   LastChanged "kexanone"
  }
  CustomStringTableItem "{66F936DFC0A12BE9}" {
   Id "KSC-Task_Exfil_Description"
   Target_en_us "Move to the exfil point."
   Target_de_de "Begebe dich zum Exfiltrationspunkt."
   Modified 1727680134
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{66F936DFCFB2C3D7}" {
   Id "KSC-Task_Exfil_Name"
   Target_en_us "Exfil"
   Target_de_de "Exfiltrieren"
   Modified 1727679985
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{6154F0E7781654D6}" {
   Id "KSC-Task_ExfilFrom_Description"
   Target_en_us "Leave the area."
   Target_de_de "Verlasse das Gebiet."
   Modified 1632973924
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6154F0E7409FA187}" {
   Id "KSC-Task_ExfilFrom_Name"
   Target_en_us "Exfil from %1"
   Target_de_de "Verlasse %1"
   Modified 1632973781
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{60ACDABEF48FC58E}" {
   Id "KSC-Task_FindIntel_Description"
   Target_en_us "Recover intel from enemy forces."
   Target_de_de "Stehle Informationsmaterial von den feindlichen Einheiten."
   Modified 1621949621
   Author "kexanone"
   LastChanged "kexanone"
  }
  CustomStringTableItem "{60ACDABEF3693FC3}" {
   Id "KSC-Task_FindIntel_Name"
   Target_en_us "Recover %1"
   Target_de_de "Finde %1"
   Modified 1621949188
   Author "kexanone"
   LastChanged "kexanone"
  }
  CustomStringTableItem "{65ECF99E0E74500D}" {
   Id "KSC-Task_FreeHostage_Description"
   Target_en_us "Free the hostage at the designated location."
   Target_de_de "Befreie die Geisel im Zielgebiet."
   Modified 1710031212
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{65ECF99E0899DFBA}" {
   Id "KSC-Task_FreeHostage_Name"
   Target_en_us "Free %1"
   Target_de_de "Befreie %1"
   Modified 1710031179
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{60ACDABEC832AEB8}" {
   Id "KSC-Task_Kill_Description"
   Target_en_us "Kill the HVT at the designated location."
   Target_de_de "Töte das hochrangige Ziel am angegeben Ort."
   Modified 1621949819
   Author "kexanone"
   LastChanged "kexanone"
  }
  CustomStringTableItem "{60ACDABECC98FAA8}" {
   Id "KSC-Task_Kill_Name"
   Target_en_us "Kill %1"
   Target_de_de "Töte %1"
   Modified 1621949644
   Author "kexanone"
   LastChanged "kexanone"
  }
  CustomStringTableItem "{66FCF16C785D54B1}" {
   Id "KSC-Task_Sabotage_Name"
   Target_en_us "Sabotage %1"
   Target_de_de "Sabotiere %1"
   Modified 1727854265
   Author "Kex"
   LastChanged "Kex"
  }
 }
}