StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{61597E9CD282A9B3}" {
   Id "KSC-Item_IntelFolder_Description"
   Target_en_us "May contain secrets."
   Target_de_de "Hat möglicherweise geheime Informationen."
   Modified 1633289427
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{61597E9CD93DBD5E}" {
   Id "KSC-Item_IntelFolder_Name"
   Target_en_us "Intelligence Folder"
   Target_de_de "Geheime Dokumente"
   Modified 1633289299
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{61530DEFF898BB6E}" {
   Id "KSC-Task_ClearArea_Description"
   Target_en_us "Clear the specified area."
   Target_de_de "Sichere das gegebene Gebiet."
   Modified 1632834224
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{61530DEFC727D0BC}" {
   Id "KSC-Task_ClearArea_Name"
   Target_en_us "Clear %1"
   Target_de_de "Sichere %1"
   Modified 1632834190
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{60AC9C2910B78278}" {
   Id "KSC-Task_Destroy_Description"
   Target_en_us "Destroy the designated target."
   Target_de_de "Zerstören Sie das angegebene Ziel."
   Modified 1621926863
   Author "kexanone"
   LastChanged "kexanone"
  }
  CustomStringTableItem "{60AC9C291F293C90}" {
   Id "KSC-Task_Destroy_Name"
   Target_en_us "Destroy %1"
   Target_de_de "Zerstöre %1"
   Modified 1621926835
   Author "kexanone"
   LastChanged "kexanone"
  }
  CustomStringTableItem "{6154F0E7781654D6}" {
   Id "KSC-Task_ExfilFrom_Description"
   Target_en_us "Leave the area."
   Target_de_de "Verlasse das Gebiet."
   Modified 1632973924
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6154F0E7409FA187}" {
   Id "KSC-Task_ExfilFrom_Name"
   Target_en_us "Exfil from %1"
   Target_de_de "Verlasse %1"
   Modified 1632973781
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{60ACDABEF48FC58E}" {
   Id "KSC-Task_FindIntel_Description"
   Target_en_us "Recover intel from enemy forces."
   Target_de_de "Stehle Informationsmaterial von den feindlichen Einheiten."
   Modified 1621949621
   Author "kexanone"
   LastChanged "kexanone"
  }
  CustomStringTableItem "{60ACDABEF3693FC3}" {
   Id "KSC-Task_FindIntel_Name"
   Target_en_us "Recover %1"
   Target_de_de "Finde %1"
   Modified 1621949188
   Author "kexanone"
   LastChanged "kexanone"
  }
  CustomStringTableItem "{60ACDABEC832AEB8}" {
   Id "KSC-Task_Kill_Description"
   Target_en_us "Kill the HVT at the designated location."
   Target_de_de "Töte das hochrangige Ziel am angegeben Ort."
   Modified 1621949819
   Author "kexanone"
   LastChanged "kexanone"
  }
  CustomStringTableItem "{60ACDABECC98FAA8}" {
   Id "KSC-Task_Kill_Name"
   Target_en_us "Kill %1"
   Target_de_de "Töte %1"
   Modified 1621949644
   Author "kexanone"
   LastChanged "kexanone"
  }
 }
}