StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{630D4CCE326184CA}" {
   Id "KRP-UserAction_BackPosition"
   Target_en_us "Put on back"
   Target_de_de "Auf den Rücken drehen"
   Modified 1661817144
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{630D4CCE36458E06}" {
   Id "KRP-UserAction_RecoveryPosition"
   Target_en_us "Put in recovery position"
   Target_de_de "In Bewusstlosenlagerung bringen"
   Modified 1661817117
   Author "Kexanone"
   LastChanged "Kexanone"
  }
 }
}