/*!
Notification IDs used by SCR_NotificationsComponent.
*/
modded enum ENotification
{
	PLAYER_INCAPACITATED,
	POSSESSED_INCAPACITATED,
	PLAYER_INCAPACITATED_PLAYER,
	PLAYER_INCAPACITATED_POSSESSED,
	POSSESSED_INCAPACITATED_PLAYER,
	POSSESSED_INCAPACITATED_POSSESSED,
	AI_INCAPACITATED_PLAYER,
	AI_INCAPACITATED_POSSESSED,
	PLAYER_REVIVED,
	POSSESSED_REVIVED,
	PLAYER_REVIVED_PLAYER,
	PLAYER_REVIVED_POSSESSED,
	POSSESSED_REVIVED_PLAYER,
	POSSESSED_REVIVED_POSSESSED,
	AI_REVIVED_PLAYER,
	AI_REVIVED_POSSESSED
};
