PersistenceSystemConfig : "{8532E1DD4E714D95}Configs/Systems/Persistence/Mission.conf" {
 Configurations {
  PersistenceConfigGroup Entities {
   Configurations {
    PersistenceConfigGroup Misc {
     Configurations {
      EntityPersistenceConfig "{6A2D7C7299D0360E}" {
       Rule ComponentClassPersistenceConfigRule "{6A2D7C729733509B}" {
        ComponentClass "KSC_EditableDestructibleStructureComponent"
       }
       Collection "{6624C4351F719B74}"
       EntitySerializer GenericEntitySerializer "{6A2D7C72802ECC64}" {
       }
       ComponentSerializers {
        KSC_EditableDestructibleStructureComponentSerializer "{6A2D7C7287F44AA9}" {
        }
       }
      }
     }
    }
   }
  }
 }
}